name: Main Pipeline

on:
  push:
    branches: [ main ]

jobs:
  CLI:
    uses: ./.github/workflows/cli.yml
  
  Deploy:
    needs: [CLI]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          docker build \
          --platform linux/amd64 \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest .

      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest