name: PR

on:
  pull_request:
    types: [assigned, opened, reopened]
    branches:
      - main

jobs:
  CLI:
    uses: ./.github/workflows/cli.yml@main
  
  Labeler:
    uses: ./.github/workflows/labeler.yml@main

  Preview:
    needs: [CLI, Labeler]
    uses: ./.github/workflows/preview.yml@main
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}